MCT-1411 Organize Pipelines using yaml anchors

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -1,9 +1,23 @@
 
 image: mediacurrent/mc-bb-pipelines:PHP8.0
 
-pipelines:
-  default:
-    - step:
+definitions:
+  caches:
+    composer-project-vendor: vendor/
+    visual-regression-ci-reference: tests/visual-regression/backstop_data/ci_reference
+    visual-regression-node-modules: tests/visual-regression/node_modules
+  services:
+    docker:
+      memory: 2048
+    mysql:
+      image: mysql:8.0
+      environment:
+        MYSQL_DATABASE: 'drupal'
+        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
+        MYSQL_USER: 'drupal'
+        MYSQL_PASSWORD: 'drupal'
+  steps:
+    - step: &build-test
         name: Build and test
         caches:
           - composer
@@ -40,6 +54,8 @@ pipelines:
           - if [ "$(ls -A web/modules/custom/)" ]; then
           - composer robo test:phpunit-tests
           - fi
+          # Set script to continue on failure.
+          - set +e
           - echo "Drupal-check custom development for Drupal 10 readiness"
           - PHPSTAN=$(./vendor/mediacurrent/ci-tests/tests/drupal-check.sh web)
           - printf '%s\n' "${PHPSTAN}"
@@ -50,8 +66,6 @@ pipelines:
           - fi
           - printf "127.0.0.1 example.mcdev" >> /etc/hosts
           - cd ./web
-          # Set script to continue on failure.
-          - set +e
           # Check for pending security updates.
           - PMSECURITY=$(../vendor/bin/drush pm:security 2>&1)
           - printf '%s\n' "${PMSECURITY}"
@@ -75,128 +89,118 @@ pipelines:
           - tests/**
           - vendor/**
           - web/**
+    - step: &a11y-regression-test
+        name: A11y and regression tests
+        script:
+          - ls -l
+          - ls -l ./vendor/bin
+          - cd web
+          - ../vendor/bin/drush sqlc < ../vendor/bin/db.sql
+          - ../vendor/bin/drush status
+          - ../vendor/bin/drush -vvv --debug runserver 8080 &
+          - sleep 3
+          - cd ..
+          - if [ "$(ls -A web/modules/custom/)" ]; then
+          # The SIMPLETEST_DB var is needed for Kernel and Functional tests.
+          - echo 'SIMPLETEST_DB="mysql://drupal:drupal@127.0.0.1:3306/drupal"' >> .env
+          # PHPUnit - Kernel and Functional tests
+          - composer robo test:phpunit-tests -- --filter="/Kernel|Functional/"
+          # PHPUnit - Drupal Test Trait ExistingSite tests
+          - DTT_BASE_URL=http://127.0.0.1:8080 ./vendor/bin/phpunit --configuration=./tests/dtt/phpunit.xml ./web/modules/custom/
+          - fi
+          # Drupal accessibility tests
+          # - echo "Accessibility tests"
+          # - pa11y --version
+          # - ./tests/pa11y/pa11y-review.sh http://127.0.0.1:8080/themes/contrib/rain_theme/dist/style-guide/section-components.html
+          # - CMD=$(./tests/pa11y/pa11y-review.sh http://127.0.0.1:8080/themes/contrib/rain_theme/dist/style-guide/section-components.html 2>&1) && printf '%s\n' "${CMD}"|| ( slackcli -h ${SLACK_CHANNEL} -e ":rage3:" -m "https://bitbucket.org/mediacurrent/${BITBUCKET_REPO_SLUG}/addon/pipelines/home#!/results/$BITBUCKET_BUILD_NUMBER ${BITBUCKET_BRANCH} error - \`\`\`${CMD}\`\`\`" && printf '%s\n' "${CMD}" && exit 1 )
+          # Drupal behat tests
+          - echo "Behat tests"
+          - ./tests/behat/behat-run.sh http://127.0.0.1:8080
+          # - CMD=$(./tests/behat/behat-run.sh http://127.0.0.1:8080 2>&1) && printf '%s\n' "${CMD}"|| ( slackcli -h ${SLACK_CHANNEL} -e ":rage3:" -m "https://bitbucket.org/mediacurrent/${BITBUCKET_REPO_SLUG}/addon/pipelines/home#!/results/$BITBUCKET_BUILD_NUMBER ${BITBUCKET_BRANCH} error - \`\`\`${CMD}\`\`\`" && printf '%s\n' "${CMD}" && exit 1 )
+        services:
+          - mysql
+    - step: &security-test
+        name: Security tests
+        caches:
+          - docker
+        script:
+          - cd web
+          - ../vendor/bin/drush sqlc < ../vendor/bin/db.sql
+          - ../vendor/bin/drush status
+          - ../vendor/bin/drush -vvv --debug runserver 172.17.0.1:8080 &
+          - cd ..
+          # OWASP Zap Baseline report
+          - echo "OWASP ZAP Baseline report"
+          - docker version
+          # Set script to continue on failure.
+          - set +e
+          - ln -s $(pwd) /zap/wrk
+          - ls -l /zap/wrk/
+          # - /zap/zap-baseline.py -c owasp-zap.conf -p owasp-zap-progress.json -t http://127.0.0.1:8080
+          - CMD=$(/zap/zap-baseline.py -d -c owasp-zap.conf -p owasp-zap-progress.json -t http://172.17.0.1:8080) && printf '%s\n' "${CMD}"|| ( slackcli -h ${SLACK_CHANNEL} -e ":lock:" -m "https://bitbucket.org/mediacurrent/${BITBUCKET_REPO_SLUG}/addon/pipelines/home#!/results/$BITBUCKET_BUILD_NUMBER - ${BITBUCKET_BRANCH} - OWASP Zap Baseline report \`\`\`${CMD}\`\`\`" && printf '%s\n' "${CMD}" && exit 1 )
+          # Set script to stop on failure.
+          - set -e
+          # Run Security Review checks
+          - cd web
+          # Check security review.
+          - ../vendor/bin/drush en security_review
+          - SECURITYREVIEW=$(../vendor/bin/drush secrev --skip=failed_logins,file_perms,private_files,views_access,trusted_hosts,field 2>&1)
+          - printf '%s\n' "${SECURITYREVIEW}"
+          - if grep -q 'failed' <<< ${SECURITYREVIEW} ; then
+          - slackcli -h ${SLACK_CHANNEL} -e ":lock:" -m "https://bitbucket.org/mediacurrent/${BITBUCKET_REPO_SLUG}/addon/pipelines/home#!/results/$BITBUCKET_BUILD_NUMBER - ${BITBUCKET_BRANCH} - secrev \`\`\`${SECURITYREVIEW}\`\`\`"
+          - exit 1
+          - fi
+        services:
+          - docker
+          - mysql
+    - step: &visual-regression-test
+        name: Visual Regression
+        caches:
+          - docker
+          - visual-regression-ci-reference
+          - visual-regression-node-modules
+        script:
+          - aws --version
+          - ls -l
+          - ls -l ./vendor/bin
+          - cd web
+          - ../vendor/bin/drush sqlc < ../vendor/bin/db.sql
+          - ../vendor/bin/drush status
+          - ../vendor/bin/drush -vvv --debug runserver 172.17.0.1:8080 &
+          - sleep 3
+          - cd ..
+          - cd tests/visual-regression
+          - chmod -R o+w ./backstop_data
+          - npm install
+          - set +e
+          # Generate new reference if needed
+          - if [ ! "$(ls -A backstop_data/ci_reference)" ]; then
+          - aws s3 cp s3://mis-ci-tests/vrt/reference-${BITBUCKET_REPO_SLUG} backstop_data --recursive
+          - if [ ! "$(ls -A backstop_data/ci_reference)" ]; then
+          - make -i ci-reference
+          - fi
+          - fi
+          - make -i ci-test
+          - aws s3 cp backstop_data s3://mis-ci-tests/vrt/test-${BITBUCKET_REPO_SLUG}-${BITBUCKET_BUILD_NUMBER} --recursive
+          # link to results posted to Bitbucket
+          - export VRT_URL="http://vrt.mediacurrent.com/test-${BITBUCKET_REPO_SLUG}-${BITBUCKET_BUILD_NUMBER}/ci_html_report/"
+          - export BUILD_STATUS="{\"key\":\"doc\", \"state\":\"SUCCESSFUL\", \"name\":\"VRT Results\", \"url\":\"${VRT_URL}\"}"
+          - curl -H "Content-Type:application/json" -X POST --user "${BB_AUTH_STRING}" -d "${BUILD_STATUS}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/commit/${BITBUCKET_COMMIT}/statuses/build"
+          # Use current develop as reference
+          - if [ "${BITBUCKET_BRANCH}" == "develop" ]; then
+          - make -i ci-approve;
+          - aws s3 cp backstop_data s3://mis-ci-tests/vrt/reference-${BITBUCKET_REPO_SLUG} --recursive
+          - fi
+        services:
+          - docker
+          - mysql
+        artifacts:
+          - tests/visual-regression/backstop_data/**
+pipelines:
+  default:
+    - step: *build-test
+
     - parallel:
-      - step:
-          name: A11y and regression tests
-          script:
-            - ls -l
-            - ls -l ./vendor/bin
-            - cd web
-            - ../vendor/bin/drush sqlc < ../vendor/bin/db.sql
-            - ../vendor/bin/drush status
-            - ../vendor/bin/drush -vvv --debug runserver 8080 &
-            - sleep 3
-            - cd ..
-            - if [ "$(ls -A web/modules/custom/)" ]; then
-            # The SIMPLETEST_DB var is needed for Kernel and Functional tests.
-            - echo 'SIMPLETEST_DB="mysql://drupal:drupal@127.0.0.1:3306/drupal"' >> .env
-            # PHPUnit - Kernel and Functional tests
-            - composer robo test:phpunit-tests -- --filter="/Kernel|Functional/"
-            # PHPUnit - Drupal Test Trait ExistingSite tests
-            - DTT_BASE_URL=http://127.0.0.1:8080 ./vendor/bin/phpunit --configuration=./tests/dtt/phpunit.xml ./web/modules/custom/
-            - fi
-            # Drupal accessibility tests
-            # - echo "Accessibility tests"
-            # - pa11y --version
-            # - ./tests/pa11y/pa11y-review.sh http://127.0.0.1:8080/themes/contrib/rain_theme/dist/style-guide/section-components.html
-            # - CMD=$(./tests/pa11y/pa11y-review.sh http://127.0.0.1:8080/themes/contrib/rain_theme/dist/style-guide/section-components.html 2>&1) && printf '%s\n' "${CMD}"|| ( slackcli -h ${SLACK_CHANNEL} -e ":rage3:" -m "https://bitbucket.org/mediacurrent/${BITBUCKET_REPO_SLUG}/addon/pipelines/home#!/results/$BITBUCKET_BUILD_NUMBER ${BITBUCKET_BRANCH} error - \`\`\`${CMD}\`\`\`" && printf '%s\n' "${CMD}" && exit 1 )
-            # Drupal behat tests
-            - echo "Behat tests"
-            - ./tests/behat/behat-run.sh http://127.0.0.1:8080
-            # - CMD=$(./tests/behat/behat-run.sh http://127.0.0.1:8080 2>&1) && printf '%s\n' "${CMD}"|| ( slackcli -h ${SLACK_CHANNEL} -e ":rage3:" -m "https://bitbucket.org/mediacurrent/${BITBUCKET_REPO_SLUG}/addon/pipelines/home#!/results/$BITBUCKET_BUILD_NUMBER ${BITBUCKET_BRANCH} error - \`\`\`${CMD}\`\`\`" && printf '%s\n' "${CMD}" && exit 1 )
-          services:
-            - mysql
-      - step:
-          name: Security tests
-          caches:
-            - docker
-          script:
-            - cd web
-            - ../vendor/bin/drush sqlc < ../vendor/bin/db.sql
-            - ../vendor/bin/drush status
-            - ../vendor/bin/drush -vvv --debug runserver 172.17.0.1:8080 &
-            - cd ..
-            # OWASP Zap Baseline report
-            - echo "OWASP ZAP Baseline report"
-            - docker version
-            # Set script to continue on failure.
-            - set +e
-            - ln -s $(pwd) /zap/wrk
-            - ls -l /zap/wrk/
-            # - /zap/zap-baseline.py -c owasp-zap.conf -p owasp-zap-progress.json -t http://127.0.0.1:8080
-            - CMD=$(/zap/zap-baseline.py -d -c owasp-zap.conf -p owasp-zap-progress.json -t http://172.17.0.1:8080) && printf '%s\n' "${CMD}"|| ( slackcli -h ${SLACK_CHANNEL} -e ":lock:" -m "https://bitbucket.org/mediacurrent/${BITBUCKET_REPO_SLUG}/addon/pipelines/home#!/results/$BITBUCKET_BUILD_NUMBER - ${BITBUCKET_BRANCH} - OWASP Zap Baseline report \`\`\`${CMD}\`\`\`" && printf '%s\n' "${CMD}" && exit 1 )
-            # Set script to stop on failure.
-            - set -e
-            # Run Security Review checks
-            - cd web
-            # Check security review.
-            - ../vendor/bin/drush en security_review
-            - SECURITYREVIEW=$(../vendor/bin/drush secrev --skip=failed_logins,file_perms,private_files,views_access,trusted_hosts,field 2>&1)
-            - printf '%s\n' "${SECURITYREVIEW}"
-            - if grep -q 'failed' <<< ${SECURITYREVIEW} ; then
-            - slackcli -h ${SLACK_CHANNEL} -e ":lock:" -m "https://bitbucket.org/mediacurrent/${BITBUCKET_REPO_SLUG}/addon/pipelines/home#!/results/$BITBUCKET_BUILD_NUMBER - ${BITBUCKET_BRANCH} - secrev \`\`\`${SECURITYREVIEW}\`\`\`"
-            - exit 1
-            - fi
-          services:
-            - docker
-            - mysql
-      - step:
-          name: Visual Regression
-          caches:
-            - docker
-            - visual-regression-ci-reference
-            - visual-regression-node-modules
-          script:
-            - aws --version
-            - ls -l
-            - ls -l ./vendor/bin
-            - cd web
-            - ../vendor/bin/drush sqlc < ../vendor/bin/db.sql
-            - ../vendor/bin/drush status
-            - ../vendor/bin/drush -vvv --debug runserver 172.17.0.1:8080 &
-            - sleep 3
-            - cd ..
-            - cd tests/visual-regression
-            - chmod -R o+w ./backstop_data
-            - npm install
-            - set +e
-            # Generate new reference if needed
-            - if [ ! "$(ls -A backstop_data/ci_reference)" ]; then
-            - aws s3 cp s3://mis-ci-tests/vrt/reference-${BITBUCKET_REPO_SLUG} backstop_data --recursive
-            - if [ ! "$(ls -A backstop_data/ci_reference)" ]; then
-            - make -i ci-reference
-            - fi
-            - fi
-            - make -i ci-test
-            - aws s3 cp backstop_data s3://mis-ci-tests/vrt/test-${BITBUCKET_REPO_SLUG}-${BITBUCKET_BUILD_NUMBER} --recursive
-            # link to results posted to Bitbucket
-            - export VRT_URL="http://vrt.mediacurrent.com/test-${BITBUCKET_REPO_SLUG}-${BITBUCKET_BUILD_NUMBER}/ci_html_report/"
-            - export BUILD_STATUS="{\"key\":\"doc\", \"state\":\"SUCCESSFUL\", \"name\":\"VRT Results\", \"url\":\"${VRT_URL}\"}"
-            - curl -H "Content-Type:application/json" -X POST --user "${BB_AUTH_STRING}" -d "${BUILD_STATUS}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/commit/${BITBUCKET_COMMIT}/statuses/build"
-            # Use current develop as reference
-            - if [ "${BITBUCKET_BRANCH}" == "develop" ]; then
-            - make -i ci-approve;
-            - aws s3 cp backstop_data s3://mis-ci-tests/vrt/reference-${BITBUCKET_REPO_SLUG} --recursive
-            - fi
-          services:
-            - docker
-            - mysql
-          artifacts:
-            - tests/visual-regression/backstop_data/**
-
-
-definitions:
-  caches:
-    composer-project-vendor: vendor/
-    visual-regression-ci-reference: tests/visual-regression/backstop_data/ci_reference
-    visual-regression-node-modules: tests/visual-regression/node_modules
-  services:
-    docker:
-      memory: 2048
-    mysql:
-      image: mysql:8.0
-      environment:
-        MYSQL_DATABASE: 'drupal'
-        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
-        MYSQL_USER: 'drupal'
-        MYSQL_PASSWORD: 'drupal'
+      - step: *a11y-regression-test
+      - step: *security-test
+      - step: *visual-regression-test
